:pencil2: _unlink: Do not remove file if not symbolic link

diff --git a/src/_unlink b/src/_unlink
--- a/src/_unlink
+++ b/src/_unlink
@@ -2,5 +2,9 @@
 
 for FILE in "$@"
 do
-  unlink ${FILE}
+  if [ -L ${FILE} ]; then
+    unlink ${FILE}
+  else
+    echo -e "ERROR: ${FILE} is not a symbolic link" >&2
+  fi
 done
